name: Convert Markdown Files
env:
  PUBLISH_DIR: publish
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v3

      - name: Install obsidian-export
        run: |
          wget https://github.com/zoni/obsidian-export/releases/download/v22.11.0/obsidian-export_Linux-x86_64.bin
          chmod +x obsidian-export_Linux-x86_64.bin

      - name: Run obsidian-export
        run: |
          rm -rf common_md && mkdir common_md
          ./obsidian-export_Linux-x86_64.bin ${{ env.PUBLISH_DIR }} common_md
